# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpLoader < Formula
  desc "Tui for configuring 1password secrets for injection into your shell environment"
  homepage "https://github.com/idiomattic/op-loader"
  url "https://github.com/idiomattic/op-loader/archive/refs/tags/v0.1.1.tar.gz"
  sha256 "d1bf03f043c7e31d3d44bef9b29bf5b4537af40bc7cbf713ee52a97d14e185bb"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/op-loader --version")
  end
end
