# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpLoader < Formula
  desc "Tui for configuring 1password secrets for injection into your shell environment"
  homepage "https://github.com/idiomattic/op-loader"
  url "https://github.com/idiomattic/op-loader/archive/refs/tags/v0.3.1.tar.gz"
  sha256 "33f962f10fd5301c5a71e1d2377000509d80b9becb8a83b4581a47a46d4ce90e"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/op-loader --version")
  end
end
