# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class OpLoader < Formula
  desc "Tui for configuring 1password secrets for injection into your shell environment"
  homepage "https://github.com/idiomattic/op-loader"
  url "https://github.com/idiomattic/op-loader/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "1771308fd805daca35a17b5e4a627ad28e83dc2c743795ad55025d1d79c441f6"

  depends_on "rust" => :build

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/op-loader --version")
  end
end
